### ISSUE TITLE
Compatibility with current versions of CiviCRM

### ISSUE THREAD

**Issue by Upperholme** [zengenuity/civicrm_groupprice#5]
Hi
This looks to be a potentially useful extension. I wonder if you have any plans to make it available for 4.6/4/7 versions of CiviCRM?

**Comment by zengenuity** [comment]
Pull request #3 supposedly makes it compatible with newer versions. I haven't been able to test it because I was no longer working with the project/client I built this for. However, it looks like I might be working with them again in the next few weeks, so I will hopefully be able to update this soon. In the meantime, if you want test that PR and comment on it to say if it works for you, that would be great.

**Comment by Upperholme** [comment]
Finally got round to checking this out with the patch from the pull request. On a site running Civi 4.6.25 the extension looks to be working well. One small point that I've noticed is that on the event information page, by default all price options are listed including those that are constrained by group, so that everyone gets to see all of the price options on that page, regardless of the options available to them when registering, which is a potential cause of confusion. In my case, I can use some CSS to hide the price option that I don't want people to see, as I'm using the extension to provide admin-only price levels for events so that admins can register speakers and event sponsors free of charge. Different use cases will of course have different needs on this, but I'd say worth adding something to the documentation to flag this up.
Given this success I'll look at using the extension on some 4.7.x sites and will aim to feed back further on the effectiveness of the pull request in supporting 4.7

**Comment by Upperholme** [comment]
Update. It transpires that using CSS to hide single price options is not straightforward as there no class or id in the rendered html to target a css rule at. I ended up removing all of the pricing options from the event information page template.

**Comment by zengenuity** [comment]
I have circled back to the original project that this was written for, and the plugin is currently working on the latest CiviCRM: 5.3.2. So, I'm going to close this old issue.

**Comment by zengenuity** [comment]
Sorry...forgot that we've been using this with a modified version of #3. Just committed our version.

**Comment by Upperholme** [comment]
Maybe update info.xml to reflect the current compatibility? Make a new release even?
